version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres__esm_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: esmdb

