spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/esmdb
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
  security:
    user:
      name: admin
      password: "^elg0R1d#]G9"
  error:
    whitelabel:
      enabled: false
    path: /error
server:
  error:
    path: /error