FROM openjdk:19-alpine
WORKDIR /app
COPY esm-0.0.1-SNAPSHOT.jar /app/esm-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "/app/esm-0.0.1-SNAPSHOT.jar"]
ENV DEVELOPER_KEY=AIzaSyDlfU5gNKiS8qEqW8yW7VHLNJO7h0vawNw